// src/components/Main.vue
<template>
  <main role="main" class="inner cover">
    <h1 class="cover-heading">Stephanus Andi Hermantyo</h1>
    <p class="lead">IT Consultant, Software &amp; Web Developer.</p>
    <p class="lead">
      <button class="btn btn-lg btn-secondary">Learn more</button>
    </p>
  </main>
</template>

<script>
export default {
  name: "Main"
};
</script>

// src/components/Main.jsx
import React from 'react';

const Main = () => (
  <main role="main" className="inner cover">
    <h1 className="cover-heading">Stephanus Andi Hermantyo</h1>
    <p className="lead">IT Consultant, Software &amp; Web Developer.</p>
    <p className="lead">
      <button className="btn btn-lg btn-secondary">Learn more</button>
    </p>
  </main>
);

export default Main;
