// src/components/Nav.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';

const Nav = () => (
  <nav className="nav nav-masthead justify-content-center">
    <NavLink exact to="/" className="nav-link">Home</NavLink>
    <NavLink to="/products" className="nav-link">Products</NavLink>
    <NavLink to="/services" className="nav-link">Services</NavLink>
    <NavLink to="/contact" className="nav-link">Contact</NavLink>
    <NavLink to="/about" className="nav-link">About</NavLink>
  </nav>
);

export default Nav;

// src/components/Nav.vue
<template>
  <nav class="nav nav-masthead justify-content-center">
    <router-link to="/" class="nav-link">Home</router-link>
    <router-link to="/products" class="nav-link">Products</router-link>
    <router-link to="/services" class="nav-link">Services</router-link>
    <router-link to="/contact" class="nav-link">Contact</router-link>
    <router-link to="/about" class="nav-link">About</router-link>
  </nav>
</template>

<script>
export default {
  name: "Nav"
};
</script>
